spring.application.name=globetrotter
spring.data.mongodb.uri=mongodb+srv://singhanshdeep3:Sak0i9PGqnPvld3A@octopus.xaoj5.mongodb.net/
spring.data.mongodb.database=octopus
server.port=8080
cloudinary.cloud_name=dougquo1c
cloudinary.api_key=683373689275274
cloudinary.api_secret=1-SjO32cX7jtWeGKSEdIRxB6Tcw
